### ISSUE TITLE
Ram 1500 Express flow chart

### ISSUE THREAD

**Issue by nourelhoda89** [nourelhoda89/automobile#1]
![express 1](https://cloud.githubusercontent.com/assets/25092904/25089663/8aade26c-2344-11e7-8852-9a66f0530946.png)

![ram flow chart2](https://cloud.githubusercontent.com/assets/25092904/25012939/92e0f4ac-2037-11e7-98f1-85bc8882f790.png)

@anthonykulis @Calvarez14 @Catyell2
first flow chart is done if you guys need to change it you can do that via lucidchart
also Cesar please be sure to fork my repo not Mr. Anthony's

**Comment by nourelhoda89** [comment]
@Calvarez14 @Catyell2 
Hopefully you guys read Mr. Kulis's email about doing a total of 7 trim per team and one extra credit for each if you wish , I know you guys were working on them, so can you let me know which ones you haven't done yet so I can do it! and please remember these need to be done by Monday!!

**Comment by nourelhoda89** [comment]
Ok guys I will be doing the Limited trim flow chart as an extra credit!!

**Comment by Catyell2** [comment]
Ok ya that's cool, sorry for not getting back to you. I plan to finish my
flow charts tonight.

**Comment by nourelhoda89** [comment]
closing since we didn't create a builder for this one
