### ISSUE TITLE
Ram 1500 parts 

### ISSUE THREAD

**Issue by nourelhoda89** [nourelhoda89/automobile#3]
![ram parts1](https://cloud.githubusercontent.com/assets/25092904/25068485/3b618dcc-222b-11e7-9a08-b6db3c54cdfa.png)
![ram parts2](https://cloud.githubusercontent.com/assets/25092904/25068486/3de1fbfe-222b-11e7-9c43-95c0e03c32d3.png)

**Comment by nourelhoda89** [comment]
@anthonykulis do you want us to specify the seating and trim color or just the fabric type?

**Comment by anthonykulis** [comment]
seating like? 4 seats, 2 seats? no. trim color is the cars paint color,
yes? as far as interior color, no.

**Comment by nourelhoda89** [comment]
@anthonykulis 
Do we have to be done coding the parts by monday or just the flow charts?

**Comment by anthonykulis** [comment]
You need to have the assignment done Friday unless I decide everyone needs
more time.
